app:
  apollo:
    api:
      import-http-api-properties:
        #平台地址
        hostUrl: http://10.50.114.180:8070/
        #登录名
        userName: apollo
        #密码
        password: admin
      export-http-api-properties:
        #平台地址a
        hostUrl: http://10.50.114.180:8070/
        #登录名
        userName: apollo
        #密码
        password: admin
      import-open-api-properties:
        #平台地址
        portalUrl: http://10.50.114.180:8070/
        #第三方应用授权
        token: 87e6e47e131f408a79bc2b727242f44c4667696a
        #操作人
        operator: apollo
      export-open-api-properties:
        #平台地址
        portalUrl: http://10.50.114.180:8070/
        #第三方应用授权
        token: 87e6e47e131f408a79bc2b727242f44c4667696a
        #操作人
        operator: apollo
    appIds:
      - CI-Test

    orgId: Conviva-BJ
    orgName: Conviva BeiJing
    apolloDataFilePath: apollo-openapi/apollo
    importEnv: DEV
