app:
  apollo:
    api:
      import-http-api-properties:
        #平台地址
        hostUrl: https://apollo-porta.conviva.com/
        #登录名
        userName: apollo
        #密码
        password: conviva123
      export-http-api-properties:
        #平台地址a
        hostUrl: https://apollo-porta.conviva.com/
        #登录名
        userName: apollo
        #密码
        password: conviva123
      import-open-api-properties:
        #平台地址
        portalUrl: https://apollo-porta.conviva.com/
        #第三方应用授权
        token: b076055e58640d12dbce1c4a40f5dafb43ef3fca
        #操作人
        operator: apollo
      export-open-api-properties:
        #平台地址
        portalUrl: https://apollo-porta.conviva.com/
        #第三方应用授权
        token: b076055e58640d12dbce1c4a40f5dafb43ef3fca
        #操作人
        operator: apollo
    appIds:
      - CI-Test

    orgId: Conviva-BJ
    orgName: Conviva Beijing
    apolloDataFilePath: apollo-openapi/apollo
    importEnv: DEV
